// Mocks generated by Mockito 5.4.0 from annotations
// in my_2048/test/game_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_2048/src/game_state.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameState].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameState extends _i1.Mock implements _i2.GameState {
  @override
  Map<String, int> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, int>{},
        returnValueForMissingStub: <String, int>{},
      ) as Map<String, int>);
  @override
  void setTopValue(int? value) => super.noSuchMethod(
        Invocation.method(
          #setTopValue,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setCurrentScore(int? value) => super.noSuchMethod(
        Invocation.method(
          #setCurrentScore,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setTopScore(int? value) => super.noSuchMethod(
        Invocation.method(
          #setTopScore,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool isCurrentScoreBiggerThanTopScore() => (super.noSuchMethod(
        Invocation.method(
          #isCurrentScoreBiggerThanTopScore,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
